Predicting Food Delivery Time - Hackathon by IMS Proschool Size of training set: 11,094 records Size of test set: 2,774 records Hackathon closes on December 10, 2019 Evaluation Metric: The final score will be calculated based on accuracy or the number of true predictions using the confusion matrix. FEATURES: Restaurant: A unique ID that represents a restaurant. Location: The location of the restaurant. Cuisines: The cuisines offered by the restaurant. Average_Cost: The average cost for one person/order. Minimum_Order: The minimum order amount. Rating: Customer rating for the restaurant. Votes: The total number of customer votes for the restaurant. Reviews: The number of customer reviews for the restaurant. Delivery_Time: The order delivery time of the restaurant. (Target Classes)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

/opt/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
data_train = pd.read_excel("Data_Train.xlsx")
data_test = pd.read_excel("Data_Test.xlsx")

In [3]:
data = data_train.copy()

In [4]:
data.head()

Restaurant                             Location  \
0    ID_6321  FTI College, Law College Road, Pune   
1    ID_2882                 Sector 3, Marathalli   
2    ID_1595                       Mumbai Central   
3    ID_5929                      Sector 1, Noida   
4    ID_6123   Rmz Centennial, I Gate, Whitefield   

                                 Cuisines Average_Cost Minimum_Order Rating  \
0  Fast Food, Rolls, Burger, Salad, Wraps         ₹200           ₹50    3.5   
1                     Ice Cream, Desserts         ₹100           ₹50    3.5   
2         Italian, Street Food, Fast Food         ₹150           ₹50    3.6   
3          Mughlai, North Indian, Chinese         ₹250           ₹99    3.7   
4                         Cafe, Beverages         ₹200           ₹99    3.2   

  Votes Reviews Delivery_Time  
0    12       4    30 minutes  
1    11       4    30 minutes  
2    99      30    65 minutes  
3   176      95    30 minutes  
4   521     235    65 minutes

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11094 entries, 0 to 11093
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Restaurant     11094 non-null  object
 1   Location       11094 non-null  object
 2   Cuisines       11094 non-null  object
 3   Average_Cost   11094 non-null  object
 4   Minimum_Order  11094 non-null  object
 5   Rating         11094 non-null  object
 6   Votes          11094 non-null  object
 7   Reviews        11094 non-null  object
 8   Delivery_Time  11094 non-null  object
dtypes: object(9)
memory usage: 780.2+ KB


In [6]:
data.shape

(11094, 9)

In [7]:
data.isnull().sum()

Restaurant       0
Location         0
Cuisines         0
Average_Cost     0
Minimum_Order    0
Rating           0
Votes            0
Reviews          0
Delivery_Time    0
dtype: int64

# Average_Cost

In [8]:
data["Average_Cost"].value_counts()

₹200      3241
₹100      2557
₹150      2462
₹250       881
₹300       537
₹350       283
₹400       282
₹50        265
₹600       154
₹500       101
₹450        63
₹550        60
₹650        55
₹800        44
₹750        38
₹900        15
₹700        15
₹1,000      12
₹850        12
₹1,200       8
₹950         4
₹1,150       1
₹2,050       1
₹1,400       1
₹1,100       1
for          1
Name: Average_Cost, dtype: int64

In [9]:
data["Average_Cost"] = data["Average_Cost"].str.replace("₹", "").str.replace(",", "").str.replace("for", "0")

In [10]:
data["Average_Cost"].value_counts()

200     3241
100     2557
150     2462
250      881
300      537
350      283
400      282
50       265
600      154
500      101
450       63
550       60
650       55
800       44
750       38
900       15
700       15
850       12
1000      12
1200       8
950        4
2050       1
0          1
1400       1
1100       1
1150       1
Name: Average_Cost, dtype: int64

In [11]:
data["Average_Cost"] = data["Average_Cost"].astype(int)

In [12]:
data.dtypes

Restaurant       object
Location         object
Cuisines         object
Average_Cost      int64
Minimum_Order    object
Rating           object
Votes            object
Reviews          object
Delivery_Time    object
dtype: object

# Minimum_Order

In [13]:
data["Minimum_Order"].value_counts()

₹50     10118
₹99       779
₹0        158
₹200        8
₹199        8
₹59         3
₹299        3
₹350        3
₹79         2
₹450        2
₹90         2
₹300        2
₹240        1
₹400        1
₹500        1
₹150        1
₹89         1
₹250        1
Name: Minimum_Order, dtype: int64

In [14]:
data["Minimum_Order"] = data["Minimum_Order"].str.replace("₹","")

In [15]:
data["Minimum_Order"] = data["Minimum_Order"].astype(int)

In [16]:
data.dtypes

Restaurant       object
Location         object
Cuisines         object
Average_Cost      int64
Minimum_Order     int64
Rating           object
Votes            object
Reviews          object
Delivery_Time    object
dtype: object

In [17]:
data.head()

Restaurant                             Location  \
0    ID_6321  FTI College, Law College Road, Pune   
1    ID_2882                 Sector 3, Marathalli   
2    ID_1595                       Mumbai Central   
3    ID_5929                      Sector 1, Noida   
4    ID_6123   Rmz Centennial, I Gate, Whitefield   

                                 Cuisines  Average_Cost  Minimum_Order Rating  \
0  Fast Food, Rolls, Burger, Salad, Wraps           200             50    3.5   
1                     Ice Cream, Desserts           100             50    3.5   
2         Italian, Street Food, Fast Food           150             50    3.6   
3          Mughlai, North Indian, Chinese           250             99    3.7   
4                         Cafe, Beverages           200             99    3.2   

  Votes Reviews Delivery_Time  
0    12       4    30 minutes  
1    11       4    30 minutes  
2    99      30    65 minutes  
3   176      95    30 minutes  
4   521     235    65 minutes

# Rating

In [18]:
data["Rating"].value_counts().sort_index()

-                     1191
2.1                      1
2.2                      1
2.3                      6
2.4                     13
2.5                     27
2.6                     42
2.7                     76
2.8                    157
2.9                    199
3.0                    302
3.1                    411
3.2                    511
3.3                    675
3.4                    718
3.5                    818
3.6                    846
3.7                    869
3.8                    800
3.9                    749
4.0                    614
4.1                    459
4.2                    272
4.3                    247
4.4                    142
4.5                     78
4.6                     41
4.7                     36
4.8                     13
4.9                      8
NEW                    758
Opening Soon            12
Temporarily Closed       2
Name: Rating, dtype: int64

In [19]:
list_of_words = ["Opening Soon", "Temporarily Closed", "-", "NEW"]

In [20]:
data.iloc[15:20]

Restaurant                                    Location  \
15    ID_6406                            Moulali, Kolkata   
16    ID_2141                             Sector 1, Noida   
17    ID_3355              Dockyard Road, Mumbai CST Area   
18    ID_5262                             Pune University   
19    ID_8148  Gora Bazar, Rajbari, North Dumdum, Kolkata   

                                          Cuisines  Average_Cost  \
15                                Biryani, Mughlai           100   
16                                         Italian           100   
17  Chinese, North Indian, South Indian, Fast Food           200   
18                                  Kerala, Bihari           150   
19                                    South Indian           100   

    Minimum_Order Rating Votes Reviews Delivery_Time  
15             50    3.6   353      53    30 minutes  
16             50      -     -       -    30 minutes  
17             50    3.7   139      47    30 minutes  
18             50      -     -       -    30 minutes  
19             50    3.7   159      46    30 minutes

In [21]:
data['Rating'][data["Rating"].isin(list_of_words)]

12         -
16         -
18         -
25         -
47       NEW
        ... 
11082      -
11084    NEW
11085      -
11086      -
11093    NEW
Name: Rating, Length: 1963, dtype: object

In [22]:
data['Rating'][data["Rating"].isin(list_of_words)] = np.nan

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [23]:
data["Rating"].value_counts(dropna = False)

NaN    1963
3.7     869
3.6     846
3.5     818
3.8     800
3.9     749
3.4     718
3.3     675
4.0     614
3.2     511
4.1     459
3.1     411
3.0     302
4.2     272
4.3     247
2.9     199
2.8     157
4.4     142
4.5      78
2.7      76
2.6      42
4.6      41
4.7      36
2.5      27
4.8      13
2.4      13
4.9       8
2.3       6
2.2       1
2.1       1
Name: Rating, dtype: int64

In [24]:
data["Rating"].fillna(0,inplace = True)

In [25]:
data['Rating']=data['Rating'].astype(float)

In [26]:
data.dtypes

Restaurant        object
Location          object
Cuisines          object
Average_Cost       int64
Minimum_Order      int64
Rating           float64
Votes             object
Reviews           object
Delivery_Time     object
dtype: object

# Votes

In [27]:
data["Votes"].value_counts().sort_index()

-       2074
10       137
100       30
1000       3
1008       4
        ... 
99        19
991        3
992        1
998        2
999        2
Name: Votes, Length: 1103, dtype: int64

In [28]:
data["Votes"] = data["Votes"].str.replace("-", "0")

In [29]:
data["Votes"].value_counts()

0       2074
4        248
6        200
7        182
9        181
        ... 
1023       1
1537       1
1122       1
3570       1
3535       1
Name: Votes, Length: 1103, dtype: int64

In [30]:
data['Votes']=data['Votes'].astype(int)

# Reviews

In [31]:
data['Reviews'].value_counts()

-       2312
2        420
3        387
1        381
4        356
        ... 
2098       1
781        1
540        1
1370       1
461        1
Name: Reviews, Length: 761, dtype: int64

In [32]:
data['Reviews']=data['Reviews'].str.replace('-','0')

In [33]:
data['Reviews'].value_counts()

0       2312
2        420
3        387
1        381
4        356
        ... 
937        1
379        1
2155       1
417        1
1673       1
Name: Reviews, Length: 761, dtype: int64

In [34]:
data['Reviews']=data['Reviews'].astype(int)

In [35]:
data.dtypes

Restaurant        object
Location          object
Cuisines          object
Average_Cost       int64
Minimum_Order      int64
Rating           float64
Votes              int64
Reviews            int64
Delivery_Time     object
dtype: object

In [36]:
data.head()

Restaurant                             Location  \
0    ID_6321  FTI College, Law College Road, Pune   
1    ID_2882                 Sector 3, Marathalli   
2    ID_1595                       Mumbai Central   
3    ID_5929                      Sector 1, Noida   
4    ID_6123   Rmz Centennial, I Gate, Whitefield   

                                 Cuisines  Average_Cost  Minimum_Order  \
0  Fast Food, Rolls, Burger, Salad, Wraps           200             50   
1                     Ice Cream, Desserts           100             50   
2         Italian, Street Food, Fast Food           150             50   
3          Mughlai, North Indian, Chinese           250             99   
4                         Cafe, Beverages           200             99   

   Rating  Votes  Reviews Delivery_Time  
0     3.5     12        4    30 minutes  
1     3.5     11        4    30 minutes  
2     3.6     99       30    65 minutes  
3     3.7    176       95    30 minutes  
4     3.2    521      235    65 minutes

# Creating Area from Location

In [37]:
data["Area"] = data["Location"].str.split(",").str[-1]

In [38]:
data.head()

Restaurant                             Location  \
0    ID_6321  FTI College, Law College Road, Pune   
1    ID_2882                 Sector 3, Marathalli   
2    ID_1595                       Mumbai Central   
3    ID_5929                      Sector 1, Noida   
4    ID_6123   Rmz Centennial, I Gate, Whitefield   

                                 Cuisines  Average_Cost  Minimum_Order  \
0  Fast Food, Rolls, Burger, Salad, Wraps           200             50   
1                     Ice Cream, Desserts           100             50   
2         Italian, Street Food, Fast Food           150             50   
3          Mughlai, North Indian, Chinese           250             99   
4                         Cafe, Beverages           200             99   

   Rating  Votes  Reviews Delivery_Time            Area  
0     3.5     12        4    30 minutes            Pune  
1     3.5     11        4    30 minutes      Marathalli  
2     3.6     99       30    65 minutes  Mumbai Central  
3     3.7    176       95    30 minutes           Noida  
4     3.2    521      235    65 minutes      Whitefield

# Restaurant

In [39]:
data['Restaurant'].nunique()

7480

In [40]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [41]:
# map function will check for index in Series data (encoded) so we have specified index in Series
mean_average_cost = data.pivot_table(index = ["Restaurant"],values = "Average_Cost")
encoded = pd.Series(data = lb.fit_transform(mean_average_cost["Average_Cost"]), index = mean_average_cost.index)
data["Restaurant"] = data["Restaurant"].map(encoded)

In [42]:
data.head()

Restaurant                             Location  \
0          33  FTI College, Law College Road, Pune   
1           3                 Sector 3, Marathalli   
2          15                       Mumbai Central   
3          49                      Sector 1, Noida   
4          33   Rmz Centennial, I Gate, Whitefield   

                                 Cuisines  Average_Cost  Minimum_Order  \
0  Fast Food, Rolls, Burger, Salad, Wraps           200             50   
1                     Ice Cream, Desserts           100             50   
2         Italian, Street Food, Fast Food           150             50   
3          Mughlai, North Indian, Chinese           250             99   
4                         Cafe, Beverages           200             99   

   Rating  Votes  Reviews Delivery_Time            Area  
0     3.5     12        4    30 minutes            Pune  
1     3.5     11        4    30 minutes      Marathalli  
2     3.6     99       30    65 minutes  Mumbai Central  
3     3.7    176       95    30 minutes           Noida  
4     3.2    521      235    65 minutes      Whitefield

# Area

In [43]:
data["Area"].nunique()

22

In [44]:
dic_area_count = data["Area"].value_counts().to_dict()
data["Area"] = data["Area"].map(dic_area_count)

In [45]:
dic_area_count

{' Noida': 2086,
 ' Pune': 1358,
 'Bangalore': 947,
 ' Mumbai CST Area': 661,
 ' Kolkata': 546,
 'Delhi University-GTB Nagar': 545,
 ' Gurgoan': 493,
 ' Timarpur': 472,
 'Mumbai Central': 459,
 ' Whitefield': 457,
 ' India Gate': 411,
 ' Marathalli': 366,
 'Majestic': 334,
 'Delhi Cantt.': 326,
 ' Maharashtra': 307,
 ' Hyderabad': 294,
 ' Delhi': 282,
 'Pune University': 278,
 'Gurgaon': 260,
 ' Mumbai': 109,
 ' Begumpet': 81,
 ' Electronic City': 22}

# Cuisines

In [46]:
data["Cuisines"].nunique()

2179

In [47]:
dic_foodorders = data["Cuisines"].value_counts().to_dict()
data["Cuisines"] =data["Cuisines"].map(dic_foodorders)

In [48]:
dic_foodorders

{'North Indian': 850,
 'North Indian, Chinese': 614,
 'Fast Food': 434,
 'South Indian': 270,
 'Chinese': 245,
 'Street Food': 181,
 'Bakery, Desserts': 171,
 'Bakery': 168,
 'North Indian, Mughlai': 155,
 'Pizza, Fast Food': 133,
 'Chinese, North Indian': 125,
 'Fast Food, Beverages': 114,
 'North Indian, Fast Food': 113,
 'North Indian, Chinese, Fast Food': 104,
 'Biryani': 103,
 'Desserts': 100,
 'Biryani, North Indian': 89,
 'Desserts, Beverages': 89,
 'North Indian, Mughlai, Chinese': 83,
 'North Indian, Chinese, Mughlai': 78,
 'Mithai, Street Food': 73,
 'Bakery, Fast Food': 71,
 'Chinese, Fast Food': 68,
 'Beverages': 68,
 'North Indian, South Indian, Chinese': 67,
 'South Indian, North Indian, Chinese': 66,
 'Burger, Fast Food': 63,
 'Ice Cream, Desserts': 61,
 'North Indian, Chinese, Biryani': 58,
 'Rolls': 57,
 'Fast Food, Chinese': 57,
 'North Indian, South Indian': 53,
 'Beverages, Fast Food': 53,
 'Ice Cream': 52,
 'Cafe': 52,
 'South Indian, Chinese': 49,
 'Pizza': 47,
 '

# Handling Outliers

In [49]:
data.head()

Restaurant                             Location  Cuisines  Average_Cost  \
0          33  FTI College, Law College Road, Pune         1           200   
1           3                 Sector 3, Marathalli        61           100   
2          15                       Mumbai Central         3           150   
3          49                      Sector 1, Noida        16           250   
4          33   Rmz Centennial, I Gate, Whitefield        14           200   

   Minimum_Order  Rating  Votes  Reviews Delivery_Time  Area  
0             50     3.5     12        4    30 minutes  1358  
1             50     3.5     11        4    30 minutes   366  
2             50     3.6     99       30    65 minutes   459  
3             99     3.7    176       95    30 minutes  2086  
4             99     3.2    521      235    65 minutes   457

In [50]:
data.shape

(11094, 10)

In [51]:
q1 = data.quantile(0.25)
q3 = data.quantile(0.75)
IQR= q3-q1 
((data< (q1-1.5*IQR)) | (data > (q3+1.5*IQR))).sum()

Area                0
Average_Cost      867
Cuisines         1898
Delivery_Time       0
Location            0
Minimum_Order     976
Rating           1963
Restaurant        838
Reviews          1490
Votes            1420
dtype: int64

# https://www.pluralsight.com/guides/cleaning-up-data-from-outliers

In [52]:
columns = ['Restaurant', 'Cuisines', 'Average_Cost', 'Minimum_Order','Rating', 'Votes', 'Reviews', 'Area']
for i in columns:
       
    q75, q25 = np.percentile(data[i], [75,25])
    iqr = q75-q25
    minimum = q25-1.5*iqr
    maximum = q75+1.5*iqr
    data[i] = np.where(data[i] < minimum, minimum, data[i])
    data[i] = np.where(data[i] > maximum, maximum, data[i])

In [53]:
#((data< (Q1-1.5*IQR)) | (data > (Q3+1.5*IQR))).sum()

In [54]:
((data< (q1-1.5*IQR)) | (data > (q3+1.5*IQR))).sum()

Area             0
Average_Cost     0
Cuisines         0
Delivery_Time    0
Location         0
Minimum_Order    0
Rating           0
Restaurant       0
Reviews          0
Votes            0
dtype: int64

In [55]:
data.shape

(11094, 10)

In [56]:
data.skew()

Restaurant       0.556002
Cuisines         1.201727
Average_Cost     0.652784
Minimum_Order    0.000000
Rating          -0.877016
Votes            1.206945
Reviews          1.196568
Area             0.868114
dtype: float64

In [57]:
cols = ['Restaurant', 'Cuisines', 'Average_Cost', 'Minimum_Order',
       'Rating', 'Votes', 'Reviews', 'Area']
for i in cols:
    data[i] = np.log(data[i]+1)   

In [58]:
data.skew()

Restaurant      -0.744979
Cuisines        -0.064990
Average_Cost    -0.428448
Minimum_Order    0.000000
Rating          -1.121949
Votes           -0.426981
Reviews         -0.120592
Area            -0.082398
dtype: float64

# Feature Selection

https://towardsdatascience.com/chi-squared-test-for-feature-selection-with-implementation-in-python-65b4ae7696db

In [59]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [60]:
x =data.drop(["Delivery_Time", "Location"], axis = 1)
y = data["Delivery_Time"]

In [61]:
#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2,k=5)
fit = bestfeatures.fit(x,y)

In [62]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)

In [63]:
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Features','Score']  #naming the dataframe columns

In [64]:
featureScores

Features         Score
0     Restaurant  2.007080e+02
1       Cuisines  1.693507e+02
2   Average_Cost  2.250893e+01
3  Minimum_Order  2.198364e-27
4         Rating  3.197954e+01
5          Votes  3.018315e+03
6        Reviews  2.967239e+03
7           Area  1.633281e+00

In [65]:
print(featureScores.nlargest(8,'Score'))

        Features         Score
5          Votes  3.018315e+03
6        Reviews  2.967239e+03
0     Restaurant  2.007080e+02
1       Cuisines  1.693507e+02
4         Rating  3.197954e+01
2   Average_Cost  2.250893e+01
7           Area  1.633281e+00
3  Minimum_Order  2.198364e-27


In [66]:
x = x.drop("Minimum_Order", axis = 1)

In [67]:
print(x.shape, y.shape)

(11094, 7) (11094,)


from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
smote=SMOTE(k_neighbors=4) # We need to specify the number of k_neighbors, the new point should consider
#smote=SMOTETomek(random_state=42)
X,Y=smote.fit_sample(x,y)

# ValueError: Expected n_neighbors <= n_samples,  but n_samples = 4, n_neighbors = 5

I had a similiar issue.

SMOTE is based in a KNN algorithm, so you need a minimal number of samples to create a new instance of this subset.

For example:

If you is trying to predict is a integer value, class 1, 2, 3, and supposing that you have just 2 samples of class 1, how to get k-3 neighbors? Will be impossible. It's too umbalanced!!
The message is pretty clear:

Expected n_neighbors <= n_samples.

So, you need have more or equals SAMPLES than neighbors, to create new instances.

I look yout dataset and you have just 4 samples of OUTPUT 1. So, the message is saying you have just 4 but I need 6 neighbors to create a new instance of them.

***You have selected a larger k than your no.of samples , k needs to be < n_samples.***

https://stackoverflow.com/questions/45943335/smote-value-error/48820222<br>
https://github.com/esteinig/netviewP/issues/2

from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
smote=SMOTE(k_neighbors=3) # We need to specify the number of k_neighbors, the new point should consider
#smote=SMOTETomek(random_state=42)
X,Y=smote.fit_sample(x,y)

# difference between smotetomek vs smote

SMOTE is an oversampling method that synthesizes new plausible examples in the majority class.<br> Tomek Links refers to a method for identifying pairs of nearest neighbors in a dataset that have different classes.

In [ ]:
#y.value_counts()

In [ ]:
#print(X.shape, Y.shape)

In [ ]:
#Y.value_counts()

# **TEST DATA CLEANING**

In [68]:
data_test = pd.read_excel("Data_Test.xlsx")
data_test.head()

Restaurant                                    Location  \
0    ID_2842  Mico Layout, Stage 2, BTM Layout,Bangalore   
1     ID_730  Mico Layout, Stage 2, BTM Layout,Bangalore   
2    ID_4620                             Sector 1, Noida   
3    ID_5470                  Babarpur, New Delhi, Delhi   
4    ID_3249                             Sector 1, Noida   

                                            Cuisines Average_Cost  \
0                    North Indian, Chinese, Assamese         ₹350   
1                                     Biryani, Kebab         ₹100   
2                                          Fast Food         ₹100   
3  Mithai, North Indian, Chinese, Fast Food, Sout...         ₹200   
4                                 Chinese, Fast Food         ₹150   

  Minimum_Order Rating Votes Reviews  
0           ₹50    4.2   361     225  
1           ₹50    NEW     -       -  
2           ₹50    3.6    36      16  
3           ₹50    3.6    66      33  
4           ₹50    2.9    38      14

In [69]:
test = data_test.copy()
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2774 entries, 0 to 2773
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Restaurant     2774 non-null   object
 1   Location       2774 non-null   object
 2   Cuisines       2774 non-null   object
 3   Average_Cost   2774 non-null   object
 4   Minimum_Order  2774 non-null   object
 5   Rating         2774 non-null   object
 6   Votes          2774 non-null   object
 7   Reviews        2774 non-null   object
dtypes: object(8)
memory usage: 173.5+ KB


In [70]:
test["Average_Cost"] = test["Average_Cost"].str.replace("₹", "").str.replace(",", "")
test["Minimum_Order"] = test["Minimum_Order"].str.replace("₹", "")
test["Minimum_Order"] = test["Minimum_Order"].astype(int)

In [71]:
test["Rating"].value_counts()

-               305
3.6             223
3.9             216
3.7             212
NEW             200
3.5             197
3.4             185
3.8             183
3.3             153
4.0             141
3.2             129
3.1             120
4.1             115
4.2              70
3.0              65
2.9              57
4.3              52
2.8              41
4.4              29
2.7              22
4.5              18
2.6               9
4.6               7
2.5               6
4.7               6
2.4               5
4.8               3
2.3               2
Opening Soon      2
2.1               1
Name: Rating, dtype: int64

In [72]:
list_of_words = ["Opening Soon", "Temporarily Closed", "-", "NEW"]
test["Rating"][test["Rating"].isin(list_of_words)] = np.nan

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [73]:
test["Rating"].value_counts(dropna = False)

NaN    507
3.6    223
3.9    216
3.7    212
3.5    197
3.4    185
3.8    183
3.3    153
4.0    141
3.2    129
3.1    120
4.1    115
4.2     70
3.0     65
2.9     57
4.3     52
2.8     41
4.4     29
2.7     22
4.5     18
2.6      9
4.6      7
2.5      6
4.7      6
2.4      5
4.8      3
2.3      2
2.1      1
Name: Rating, dtype: int64

In [74]:
test["Rating"].fillna(0,inplace = True)

In [75]:
test["Votes"].value_counts()

-      542
7       60
9       57
6       55
5       51
      ... 
422      1
566      1
666      1
510      1
798      1
Name: Votes, Length: 580, dtype: int64

In [76]:
test["Votes"] = test["Votes"].str.replace("-", "0")

In [77]:
test["Reviews"] = test["Reviews"].str.replace("-", "0")

In [78]:
test.isnull().sum()

Restaurant       0
Location         0
Cuisines         0
Average_Cost     0
Minimum_Order    0
Rating           0
Votes            0
Reviews          0
dtype: int64

In [79]:
test["Rating"] = test["Rating"].astype(float)
test["Votes"] = test["Votes"].astype(int)
test["Reviews"] = test["Reviews"].astype(int)
test["Average_Cost"] = test["Average_Cost"].astype(int)

In [80]:
test["Area"] = data["Location"].str.split(",").str[-1]

In [81]:
mean_average_cost1 = test.pivot_table(index = ["Restaurant"],values = "Average_Cost")
encoded1 = pd.Series(data = lb.fit_transform(mean_average_cost1["Average_Cost"]), index = mean_average_cost1.index)
test["Restaurant"] = test["Restaurant"].map(encoded1)

In [82]:
dic_area_count = test["Area"].value_counts().to_dict()
test["Area"] = test["Area"].map(dic_area_count)

In [83]:
dic_foodorders = test["Cuisines"].value_counts().to_dict()
test["Cuisines"] =test["Cuisines"].map(dic_foodorders)

In [84]:
test.head()

Restaurant                                    Location  Cuisines  \
0          20  Mico Layout, Stage 2, BTM Layout,Bangalore         1   
1           2  Mico Layout, Stage 2, BTM Layout,Bangalore         6   
2           2                             Sector 1, Noida       119   
3          10                  Babarpur, New Delhi, Delhi         1   
4           6                             Sector 1, Noida        23   

   Average_Cost  Minimum_Order  Rating  Votes  Reviews  Area  
0           350             50     4.2    361      225   342  
1           100             50     0.0      0        0    79  
2           100             50     3.6     36       16   134  
3           200             50     3.6     66       33   503  
4           150             50     2.9     38       14   119

In [85]:
Q1 = test.quantile(0.25)
Q3 = test.quantile(0.75)
IQR= Q3-Q1 
((test< (Q1-1.5*IQR)) | (test > (Q3+1.5*IQR))).sum()

Area               0
Average_Cost     162
Cuisines         517
Location           0
Minimum_Order    218
Rating           507
Restaurant        97
Reviews          364
Votes            341
dtype: int64

In [86]:
columns_1 = ['Restaurant', 'Cuisines', 'Average_Cost', 'Minimum_Order','Rating', 'Votes', 'Reviews']
for i in columns_1:
       
    q75, q25 = np.percentile(test[i], [75,25])
    iqr = q75-q25
    minimum = q25-1.5*iqr
    maximum = q75+1.5*iqr
    test[i] = np.where(test[i] < minimum, minimum, test[i])
    test[i] = np.where(test[i] > maximum, maximum, test[i])

In [87]:
((test< (Q1-1.5*IQR)) | (test > (Q3+1.5*IQR))).sum()

Area             0
Average_Cost     0
Cuisines         0
Location         0
Minimum_Order    0
Rating           0
Restaurant       0
Reviews          0
Votes            0
dtype: int64

In [88]:
test.skew()

Restaurant       0.682158
Cuisines         1.077220
Average_Cost     0.618555
Minimum_Order    0.000000
Rating          -0.868044
Votes            1.207319
Reviews          1.209794
Area             0.774490
dtype: float64

In [89]:
cols_1= ['Restaurant', 'Cuisines', 'Average_Cost', 'Minimum_Order',
       'Rating', 'Votes', 'Reviews', 'Area']
for i in cols_1:
    test[i] = np.log(test[i]+1)  

In [90]:
test.skew()

Restaurant      -0.626999
Cuisines         0.146204
Average_Cost    -0.331594
Minimum_Order    0.000000
Rating          -1.096908
Votes           -0.405331
Reviews         -0.102511
Area            -0.119786
dtype: float64

In [91]:
test.head()

Restaurant                                    Location  Cuisines  \
0    3.044522  Mico Layout, Stage 2, BTM Layout,Bangalore  0.693147   
1    1.098612  Mico Layout, Stage 2, BTM Layout,Bangalore  1.945910   
2    1.098612                             Sector 1, Noida  4.532599   
3    2.397895                  Babarpur, New Delhi, Delhi  0.693147   
4    1.945910                             Sector 1, Noida  3.178054   

   Average_Cost  Minimum_Order    Rating     Votes   Reviews      Area  
0      5.860786       3.931826  1.648659  5.891644  5.007296  5.837730  
1      4.615121       3.931826  1.029619  0.000000  0.000000  4.382027  
2      4.615121       3.931826  1.526056  3.610918  2.833213  4.905275  
3      5.303305       3.931826  1.526056  4.204693  3.526361  6.222576  
4      5.017280       3.931826  1.360977  3.663562  2.708050  4.787492

In [92]:
df_test = test.drop(["Location", "Minimum_Order"],axis = 1)

In [132]:
df_test.head()

Restaurant  Cuisines  Average_Cost    Rating     Votes   Reviews      Area
0    3.044522  0.693147      5.860786  1.648659  5.891644  5.007296  5.837730
1    1.098612  1.945910      4.615121  1.029619  0.000000  0.000000  4.382027
2    1.098612  4.532599      4.615121  1.526056  3.610918  2.833213  4.905275
3    2.397895  0.693147      5.303305  1.526056  4.204693  3.526361  6.222576
4    1.945910  3.178054      5.017280  1.360977  3.663562  2.708050  4.787492

In [164]:
df_test.shape

(2774, 7)

# Modeling and Predicting of Imbalanced dataset

In [94]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score

In [95]:
x = data.drop(["Delivery_Time", "Location"], axis = 1)
y = data["Delivery_Time"]

In [96]:
x = x.drop("Minimum_Order", axis = 1)

In [104]:
x

Restaurant  Cuisines  Average_Cost    Rating     Votes   Reviews  \
0        3.526361  0.693147      5.303305  1.504077  2.564949  1.609438   
1        1.386294  4.127134      4.615121  1.504077  2.484907  1.609438   
2        2.772589  1.386294      5.017280  1.526056  4.605170  3.433987   
3        3.912023  2.833213      5.525453  1.547563  5.176150  4.564348   
4        3.526361  2.708050      5.303305  1.435085  5.948035  5.046646   
...           ...       ...           ...       ...       ...       ...   
11089    3.912023  0.693147      5.525453  1.648659  5.789960  5.046646   
11090    1.386294  6.028279      4.615121  1.526056  3.610918  2.833213   
11091    1.386294  2.397895      4.615121  1.504077  3.828641  2.944439   
11092    1.386294  6.028279      4.615121  1.410987  3.218876  2.302585   
11093    1.386294  6.028279      4.615121  1.029619  0.000000  0.000000   

           Area  
0      7.214504  
1      5.905362  
2      6.131226  
3      7.643483  
4      6.126869  
...         ...  
11089  3.135494  
11090  7.643483  
11091  5.814131  
11092  5.905362  
11093  5.564520  

[11094 rows x 7 columns]

In [139]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.25,random_state = 42)

In [140]:
x_test.shape

(2774, 7)

In [99]:
from xgboost import XGBClassifier
xgb = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.6, gamma=0.3,
              learning_rate=0.25, max_delta_step=0, max_depth=64,
              min_child_weight=3, missing=None, n_estimators=500, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [100]:
xgb.fit(x_train, y_train)

[15:37:55] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:480: 
Parameters: { scale_pos_weight } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.6, gamma=0.3, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.25, max_delta_step=0, max_depth=64,
              min_child_weight=3, missing=None, monotone_constraints='()',
              n_estimators=500, n_jobs=1, nthread=1, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, seed=0, silent=None,
              subsample=1, tree_method='exact', validate_parameters=1,
              verbosity=1)

In [128]:
xgb_pred = xgb.predict(df_test)

In [130]:
df_test.shape

(2774, 7)

In [131]:
xgb_pred.shape

(2774,)

In [110]:
print(accuracy_score(y_test, xgb_pred))
print(classification_report(y_test, xgb_pred))
print("\n")
print(confusion_matrix(y_test, xgb_pred))

0.5342465753424658
              precision    recall  f1-score   support

  10 minutes       0.00      0.00      0.00         1
 120 minutes       0.00      0.00      0.00        14
  20 minutes       0.00      0.00      0.00         1
  30 minutes       0.67      0.70      0.69      1876
  45 minutes       0.23      0.27      0.25       650
  65 minutes       0.01      0.00      0.01       231
  80 minutes       0.00      0.00      0.00         1

    accuracy                           0.53      2774
   macro avg       0.13      0.14      0.13      2774
weighted avg       0.51      0.53      0.52      2774



[[   0    0    0    1    0    0    0]
 [   0    0    0    9    4    1    0]
 [   0    0    0    0    1    0    0]
 [   0    0    0 1307  505   64    0]
 [   0    0    0  460  174   16    0]
 [   0    0    1  162   67    1    0]
 [   0    0    0    1    0    0    0]]


# Modeling and Predicting by Handling Imbalanced Dataset

In [219]:
x = data.drop(["Delivery_Time", "Location"], axis = 1)
y = data["Delivery_Time"]

In [220]:
x = x.drop("Minimum_Order", axis = 1)

In [221]:
x

Restaurant  Cuisines  Average_Cost    Rating     Votes   Reviews  \
0        3.526361  0.693147      5.303305  1.504077  2.564949  1.609438   
1        1.386294  4.127134      4.615121  1.504077  2.484907  1.609438   
2        2.772589  1.386294      5.017280  1.526056  4.605170  3.433987   
3        3.912023  2.833213      5.525453  1.547563  5.176150  4.564348   
4        3.526361  2.708050      5.303305  1.435085  5.948035  5.046646   
...           ...       ...           ...       ...       ...       ...   
11089    3.912023  0.693147      5.525453  1.648659  5.789960  5.046646   
11090    1.386294  6.028279      4.615121  1.526056  3.610918  2.833213   
11091    1.386294  2.397895      4.615121  1.504077  3.828641  2.944439   
11092    1.386294  6.028279      4.615121  1.410987  3.218876  2.302585   
11093    1.386294  6.028279      4.615121  1.029619  0.000000  0.000000   

           Area  
0      7.214504  
1      5.905362  
2      6.131226  
3      7.643483  
4      6.126869  
...         ...  
11089  3.135494  
11090  7.643483  
11091  5.814131  
11092  5.905362  
11093  5.564520  

[11094 rows x 7 columns]

In [222]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.25,random_state = 42)

In [223]:
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
smote=SMOTE(k_neighbors=2) # 0.7627627627627628
X,Y=smote.fit_sample(x_train,y_train)

#WITHOUT TRAIN_TEST_SPLIT
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
smote=SMOTE(k_neighbors=2) # 0.7627627627627628
X,Y=smote.fit_sample(x,y)

In [224]:
# from imblearn.combine import SMOTETomek
# from imblearn.over_sampling import ADASYN
# adasyn=ADASYN("not majority",n_neighbors = 2) # 0.7627627627627628
# X,Y=adasyn.fit_sample(x_train,y_train)

In [225]:
from collections import Counter
print("Before:", Counter(y_train))
print("After:", Counter(Y))

Before: Counter({'30 minutes': 5530, '45 minutes': 2015, '65 minutes': 692, '120 minutes': 48, '20 minutes': 19, '80 minutes': 13, '10 minutes': 3})
After: Counter({'45 minutes': 5530, '30 minutes': 5530, '65 minutes': 5530, '120 minutes': 5530, '20 minutes': 5530, '80 minutes': 5530, '10 minutes': 5530})


In [226]:
from xgboost import XGBClassifier
xgb = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.6, gamma=0.3,
              learning_rate=0.25, max_delta_step=0, max_depth=64,
              min_child_weight=3, missing=None, n_estimators=500, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [227]:
xgb.fit(X, Y)

[16:06:04] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:480: 
Parameters: { scale_pos_weight } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.6, gamma=0.3, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.25, max_delta_step=0, max_depth=64,
              min_child_weight=3, missing=None, monotone_constraints='()',
              n_estimators=500, n_jobs=1, nthread=1, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, seed=0, silent=None,
              subsample=1, tree_method='exact', validate_parameters=1,
              verbosity=1)

In [228]:
xgb_pred = xgb.predict(x_test)

In [229]:
xgb_pred.shape

(2774,)

In [230]:
y_test.shape

(2774,)

In [231]:
print(accuracy_score(y_test, xgb_pred))
print(classification_report(y_test, xgb_pred))
print("\n")
print(confusion_matrix(y_test, xgb_pred))

0.7703677000720981
              precision    recall  f1-score   support

  10 minutes       0.00      0.00      0.00         1
 120 minutes       0.57      0.29      0.38        14
  20 minutes       0.20      1.00      0.33         1
  30 minutes       0.84      0.89      0.87      1876
  45 minutes       0.63      0.59      0.61       650
  65 minutes       0.47      0.35      0.40       231
  80 minutes       0.50      1.00      0.67         1

    accuracy                           0.77      2774
   macro avg       0.46      0.59      0.47      2774
weighted avg       0.76      0.77      0.76      2774



[[   0    0    0    1    0    0    0]
 [   0    4    0    8    2    0    0]
 [   0    0    1    0    0    0    0]
 [   1    2    2 1667  161   43    0]
 [   0    1    2  213  382   51    1]
 [   1    0    0   85   63   82    0]
 [   0    0    0    0    0    0    1]]


# RandomForest

In [232]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
rfc = RandomForestClassifier(criterion= "entropy", n_estimators = 500)

In [233]:
rfc.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=500)

In [234]:
rfc_pred = rfc.predict(x_test)

In [235]:
print(accuracy_score(y_test, rfc_pred))
print(classification_report(y_test, rfc_pred))
print("\n")
print(confusion_matrix(y_test, rfc_pred))

0.7635183850036049
              precision    recall  f1-score   support

  10 minutes       0.00      0.00      0.00         1
 120 minutes       0.44      0.29      0.35        14
  20 minutes       0.00      0.00      0.00         1
  30 minutes       0.86      0.87      0.86      1876
  45 minutes       0.60      0.62      0.61       650
  65 minutes       0.43      0.35      0.39       231
  80 minutes       0.25      1.00      0.40         1

    accuracy                           0.76      2774
   macro avg       0.37      0.45      0.37      2774
weighted avg       0.76      0.76      0.76      2774



[[   0    0    0    1    0    0    0]
 [   0    4    0    6    4    0    0]
 [   0    0    0    0    0    1    0]
 [   1    4    2 1630  189   50    0]
 [   0    1    1  188  402   57    1]
 [   1    0    1   73   73   81    2]
 [   0    0    0    0    0    0    1]]


# Logistic Regression

In [236]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(multi_class = 'ovr')

In [237]:
logr.fit(X,Y)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(multi_class='ovr')

In [238]:
logr_pred = logr.predict(x_test)

In [239]:
print(accuracy_score(y_test, logr_pred))
print(classification_report(y_test, logr_pred))
print("\n")
print(confusion_matrix(y_test, logr_pred))

0.3731074260994953
              precision    recall  f1-score   support

  10 minutes       0.01      1.00      0.01         1
 120 minutes       0.01      0.14      0.03        14
  20 minutes       0.00      1.00      0.00         1
  30 minutes       0.88      0.47      0.61      1876
  45 minutes       0.46      0.19      0.27       650
  65 minutes       0.15      0.11      0.13       231
  80 minutes       0.00      1.00      0.00         1

    accuracy                           0.37      2774
   macro avg       0.22      0.56      0.15      2774
weighted avg       0.72      0.37      0.49      2774



[[  1   0   0   0   0   0   0]
 [  1   2   3   4   1   1   2]
 [  0   0   1   0   0   0   0]
 [142  83 385 878 113  71 204]
 [ 15  41  77  94 126  72 225]
 [  9  19  43  22  32  26  80]
 [  0   0   0   0   0   0   1]]


# K Nearesr Neighbor

In [244]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [246]:
knn.fit(X, Y)

KNeighborsClassifier(n_neighbors=3)

In [247]:
knn_pred = knn.predict(x_test)

In [248]:
print(accuracy_score(y_test, knn_pred))
print(classification_report(y_test, knn_pred))
print("\n")
print(confusion_matrix(y_test, knn_pred))

0.6254506128334535
              precision    recall  f1-score   support

  10 minutes       0.00      0.00      0.00         1
 120 minutes       0.10      0.36      0.15        14
  20 minutes       0.03      1.00      0.06         1
  30 minutes       0.84      0.69      0.76      1876
  45 minutes       0.45      0.53      0.49       650
  65 minutes       0.26      0.40      0.31       231
  80 minutes       0.04      1.00      0.07         1

    accuracy                           0.63      2774
   macro avg       0.24      0.57      0.26      2774
weighted avg       0.70      0.63      0.65      2774



[[   0    0    0    1    0    0    0]
 [   0    5    0    5    3    1    0]
 [   0    0    1    0    0    0    0]
 [   4   33   26 1293  337  170   13]
 [   1    8    3  186  342   99   11]
 [   0    5    2   54   74   93    3]
 [   0    0    0    0    0    0    1]]
